### ISSUE TITLE
Update readme for project 

### ISSUE THREAD

**Issue by omideleayo** [albertolalanda/new-ultrasonic-fork-for-MyMusicQoE#9]
Do you mind if I make a new readme for this wonderful app, and maybe add some FAQ files to be merged into the project.

**Comment by tiagoapmartins** [comment]
I'm sorry but this is an academic project and the main information will be on the report.
I don't think a FAQ is needed in this case.

Regards,
Tiago Martins

**Comment by omideleayo** [comment]
Oh sorry, thanks for the reply
